---
title: "data_aquisition_twitter"
author: "Stefan Haußner"
date: "12 Juli 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
library(openxlsx)
```

#Einlesen der Daten

Liste aller MEPs (Stand 12.07.2019) mit Parteizugehörigkeit, Land und Fraktion und dazugehörigem Twitternamen.

Link user_ids to screen_name in meps_list_withtwitter.

```{r}
lookup_userids <- function(user_name) {
  user_info <- rtweet::lookup_users(user_name, parse = TRUE)
  return(user_info$screen_name)
}

meps_full_list <- openxlsx::read.xlsx("../data/list_meps_2019.xlsx", sheet = 1) %>% tbl_df()
meps_full_list

meps_list_withtwitter <- meps_full_list %>% 
  filter(!is.na(twitter_name)) %>% 
  mutate(twitter_id = lookup_userids(twitter_name))
meps_list_withtwitter
```

Test with 5 users

```{r}

<<<<<<< Updated upstream
test_meps_list_withtwitter <- meps_list_withtwitter %>% sample_n(15)


test_allfriends <- rtweet::get_friends(users = test_meps_list_withtwitter$twitter_id, retryonratelimit = TRUE)

test_allfriends %>% 
  filter(user_id %in% test_meps_list_withtwitter$twitter_id)
=======
edge_list <- allfriends %>% 
  filter(user_id %in% meps_list_withtwitter$twitter_id)
>>>>>>> Stashed changes
```



